package com.icodejava.research.nlp.database;

public interface Tables {
	
	String ARTICLES="ARTICLES";
	String WEBSITES="WEBSITES";
	String SENTENCES="SENTENCES";
	String WORDS="WORDS";
	String WORDS_UNREFERENCED="WORDS_UNREFERENCED";
	String SENTENCE_UNREFERENCED="SENTENCE_UNREFERENCED";
	String WORD_FREQUENCY="WORD_FREQUENCY";
	String WEBCRWAL_ACTIVITY="WEBCRAWL_ACTIVITY";
	String WORDS_LINKAGE="WORDS_LINKAGE";
	
	String KNOWN_ENTITIES="KNOWN_ENTITIES";
}
