package com.icodejava.research.nlp.database;

public interface Tables {
	
	String ARTICLES="ARTICLES";
	String WEBSITES="WEBSITES";
	String SENTENCES="SENTENCES";
	String WORDS="WORDS";
	String WORDS_UNREFERENCED="WORDS_UNREFERENCED";
	String WORD_FREQUENCY="WORD_FREQUENCY";
	String WEBCRWAL_ACTIVITY="WEBCRAWL_ACTIVITY";
	String WORD_COMBINATION_TWO="WORD_COMBINATION_TWO";
	String WORD_COMBINATION_THREE="WORD_COMBINATION_THREE";
	String WORD_COMBINATION_FOUR="WORD_COMBINATION_FOUR";
	String WORD_COMBINATION_FIVE="WORD_COMBINATION_FIVE";
	String WORD_COMBINATION_SIX="WORD_COMBINATION_SIX";
	String WORD_COMBINATION_SEVEN="WORD_COMBINATION_SEVEN";
	String WORD_COMBINATION_EIGHT="WORD_COMBINATION_EIGHT";
	String WORD_COMBINATION_NINE="WORD_COMBINATION_NINE";
	String WORD_COMBINATION_TEN="WORD_COMBINATION_TEN";
}
